# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/classroom_topics", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ClassroomTopic. As you add validations to ClassroomTopic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ClassroomTopic.create! valid_attributes
      get classroom_topics_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      classroom_topic = ClassroomTopic.create! valid_attributes
      get classroom_topic_url(classroom_topic)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_classroom_topic_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      classroom_topic = ClassroomTopic.create! valid_attributes
      get edit_classroom_topic_url(classroom_topic)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ClassroomTopic" do
        expect {
          post classroom_topics_url, params: { classroom_topic: valid_attributes }
        }.to change(ClassroomTopic, :count).by(1)
      end

      it "redirects to the created classroom_topic" do
        post classroom_topics_url, params: { classroom_topic: valid_attributes }
        expect(response).to redirect_to(classroom_topic_url(ClassroomTopic.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ClassroomTopic" do
        expect {
          post classroom_topics_url, params: { classroom_topic: invalid_attributes }
        }.not_to change(ClassroomTopic, :count)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post classroom_topics_url, params: { classroom_topic: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested classroom_topic" do
        classroom_topic = ClassroomTopic.create! valid_attributes
        patch classroom_topic_url(classroom_topic), params: { classroom_topic: new_attributes }
        classroom_topic.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the classroom_topic" do
        classroom_topic = ClassroomTopic.create! valid_attributes
        patch classroom_topic_url(classroom_topic), params: { classroom_topic: new_attributes }
        classroom_topic.reload
        expect(response).to redirect_to(classroom_topic_url(classroom_topic))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        classroom_topic = ClassroomTopic.create! valid_attributes
        patch classroom_topic_url(classroom_topic), params: { classroom_topic: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested classroom_topic" do
      classroom_topic = ClassroomTopic.create! valid_attributes
      expect {
        delete classroom_topic_url(classroom_topic)
      }.to change(ClassroomTopic, :count).by(-1)
    end

    it "redirects to the classroom_topics list" do
      classroom_topic = ClassroomTopic.create! valid_attributes
      delete classroom_topic_url(classroom_topic)
      expect(response).to redirect_to(classroom_topics_url)
    end
  end
end
